```js
class Promise {
  constructor(exectorCallback) {
    this.status = "pending";
    this.value = undefined;
    this.fulfilledFns = [];
    this.rejectedFns = [];
    let resolve = (result) => {
      let timer = setTimeout(() => {
        clearTimeout(timer);
        timer = null;
        if (this.status === "pending") {
          this.status = "resolved";
          this.value = result;
          this.fulfilledFns.forEach((item) => item(this.value));
        }
      });
    };
    let reject = (reason) => {
      let timer = setTimeout(() => {
        clearTimeout(timer);
        timer = null;
        if (this.status === "pending") {
          this.status = "rejected";
          this.value = reason;
          this.rejectedFns.forEach((item) => item(this.value));
        }
      });
    };
    try {
      exectorCallback(resolve, reject);
    } catch (error) {
      reject(error);
    }
  }

  then(fulfilledFn, rejectedFn) {
    typeof fulfilledFn !== "function"
      ? (res) => {
          return res;
        }
      : null;

    typeof rejectedFn !== "function"
      ? (reason) => {
          throw new Error(reason);
        }
      : null;

    return new Promise((resolve, reject) => {
      this.fulfilledFns.push((value) => {
        try {
          let x = fulfilledFn(value);
          x instanceof Promise ? x.then(resolve, reject) : resolve(x);
        } catch (error) {
          reject(error);
        }
      });
      this.rejectedFns.push((value) => {
        try {
          let x = rejectedFn(value);
          x instanceof Promise ? x.then(resolve, reject) : reject(x);
        } catch (error) {
          reject(error);
        }
      });
    });
  }

  catch(rejectedFn) {
    return this.then(null, rejectedFn);
  }

  static all(promiseArr = []) {
    return new Promise((resolve, reject) => {
      let resArr = [];
      let index = 0;
      for (let i = 0; i < promiseArr.length; i++) {
        try {
          if (promiseArr[i] instanceof Promise) {
            promiseArr[i].then(
              (res) => {
                index++;
                resArr[i] = res;
                if (index === promiseArr.length) {
                  resolve(resArr);
                }
              },
              (err) => {
                reject(err);
              }
            );
          } else {
            resArr[i] = promiseArr[i];
          }
        } catch (error) {
          reject(error);
        }
      }
    });
  }
  // [p1,p2,p3]  传参是一个数组
  static race(promiseArr = []) {
    return new Promise((resolve, reject) => {
      for (let i = 0; i < promiseArr.length; i++) {
        if (promiseArr[i] instanceof Promise) {
          promiseArr[i].then(
            (res) => {
              resolve(res);
              return;
            },
            (err) => {
              reject(err);
              return;
            }
          );
        } else {
          resolve(promiseArr[i]);
          return;
        }
      }
    });
  }

  static resolve(result) {
    return new Promise((resolve, reject) => {
      resolve(result);
    });
  }

  static reject(reason) {
    return new Promise((resolve, reject) => {
      reject(reason);
    });
  }
}

module.exports = Promise;
```

```
promise.then(data => {
    // 1 假如返回的是一个普通值，会把结果传入下一次then的成功回调
    // 2 发生错误，会被下一次的then的失败捕获
    // 3 如果返回Promise实例，根据该promise的状态对应调用下一次的then
    console.log('110');
    console.log(data);
    // throw new Error('出错了');
    return new Promise((resolve, reject) => {
        resolve('ok');
    });
}, err =>  {
    console.log(err); //1 假如返回的是一个普通值，会把结果传入下一次then的成功回调
    return 10;
}).then(data => {
    console.log('success' + data);
}, err => {
    console.log('error' + err);
});
```
